### ISSUE TITLE
Bugs in gameplay

### ISSUE THREAD

**Issue by Tarell13** [johnklima/TD2024#3]
A few bugs found (finally had time to playtest)
Added some videos to Google Drive - Check link.

- Bottles float away (Might be worth noting for when moved)
- Enemy floats in the sky
- Aim is sticky if aim is high (elevation)
- Mixed bottles can not stack, even if the ingredients are used. (Can be confusing mayhaps?)
- Mix button has a strange "Hitbox"
- Heal is not oneshot?
- Menu has issues.

https://drive.google.com/drive/u/0/folders/12K-hnIdP-TIoKVuG6Hmg-ch6Gvio27RK

**Comment by OikoumE** [comment]
nice! 
i had to request access to the drive link

mixed bottles do not stack, only ingredients, as per GDD.
i am unsure if heal is supposed to be oneshot, or how much its supposed to heal pr shot. ( i just make things xD )

bottles floating away im not sure what means or potential cause
enemies floating has been noticed, but thought to be fixed, will look into this
mix button, will look into

menu has issue: please elaborate

**Comment by OikoumE** [comment]
you have vids! checking now ;)

**Comment by OikoumE** [comment]
floating bottle. had you thrown it?

**Comment by OikoumE** [comment]
answers/note to self
- Bottles float away (Might be worth noting for when moved)
    - if been thrown, should disappear on collision. migth have hit a test object that doesnt kill it.
- Enemy floats in the sky
    - overlapping collision boxes, will fix
- Aim is sticky if aim is high (elevation)
    - raycast hits no target, raycastHit == null, line renderer gets no end point
- Mixed bottles can not stack, even if the ingredients are used. (Can be confusing mayhaps?)
    - potions dont stack, only ingredients according to GGD
- Mix button has a strange "Hitbox"
    - known, will fix.
    - mix button is disabled until 2 ingredients are slotted. will increase "disabled" feedback
- Heal is not oneshot?
    - system is built, but not adjusted according to "rules" (needs QA)
- Menu has issues.
    - system build, missing componends/QA - i will improve the system also

apparently i didnt see all the vids.
floating bottles. will investigate. when throwing item at item

**Comment by OikoumE** [comment]
# Fixes:
- Menu issues fix:
    - https://github.com/johnklima/TD2024/assets/83828323/b6bc4c89-26f0-472d-b0ef-4df98902e479
- Floating Enemy:
    - Colliders rearranged, ignore layers set.
- Sticky Aim:
    - added bounding box for raycast (will add roof (not present in video))
    - https://github.com/johnklima/TD2024/assets/83828323/dfffaffb-215c-4dde-b5ee-4fb49a8b8aca
- mix button:
    - changed to correct sprite
- healing area:
    - added "isOneShot" option to HealingArea.cs (HealthPlatformPrefab)

**Comment by OikoumE** [comment]
bugs fixed. QA need to handle the rest

**Comment by OikoumE** [comment]
bugs fixed. QA need to handle the rest
